### ISSUE TITLE
fix form-field mod attr

### ISSUE THREAD

**Issue by adinvadim** [bem-contrib/bem-forms#187]
https://github.com/bem-contrib/bem-forms/blob/v1.0.0/common.blocks/form-field/form-field.bemhtml

```
    attrs()({ 'data-name' : this.ctx.name })
```

```
    attrs()(function() {
        return { 'data-name' : this.ctx.name }
    })
```

иначе 
```
/Volumes/data/Developing/video/vps/frontend/themes/basic/bundles/index/index.bemhtml.js:2401
    attrs()({ 'data-name' : this.ctx.name })
                                    ^

TypeError: Cannot read property 'name' of undefined
    at Object.<anonymous> (/Volumes/data/Developing/video/vps/frontend/themes/basic/bundles/index/index.bemhtml.js:2401:37)
    at Tree.build (/Volumes/data/Developing/video/vps/frontend/themes/basic/bundles/index/index.bemhtml.js:1573:13)
    at BEMHTML.compile (/Volumes/data/Developing/video/vps/frontend/themes/basic/bundles/index/index.bemhtml.js:734:18)
    at buildBemXjst (/Volumes/data/Developing/video/vps/frontend/themes/basic/bundles/index/index.bemhtml.js:1901:5)
    at /Volumes/data/Developing/video/vps/frontend/themes/basic/bundles/index/index.bemhtml.js:3404:30
    at Object.<anonymous> (/Volumes/data/Developing/video/vps/frontend/themes/basic/bundles/index/index.bemhtml.js:3438:3)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by adinvadim** [comment]
Сейчас пришлю исправление

**Comment by adinvadim** [comment]
https://github.com/bem-contrib/bem-forms/pull/188
