### ISSUE TITLE
Тесты работают?

### ISSUE THREAD

**Issue by JiLiZART** [bem-contrib/bem-forms#209]
пытаюсь запустить тесты через `npm run specs` и получаю

```
02:11:52.173 - [rebuild] [common.specs/form-field_type_select/form-field_type_select.pre.spec.js] file-merge
02:11:52.200 - [rebuild] [common.specs/form-field_type_select/form-field_type_select.spec.js] borschik
02:11:52.269 - [spec] [common.specs/form-field_type_checkbox/form-field_type_checkbox.html]

02:11:52.272 - [spec] [common.specs/form-field_type_checkbox-group/form-field_type_checkbox-group.html]

02:11:52.274 - [spec] [common.specs/form-field_type_attach/form-field_type_attach.html]

02:11:52.276 - [spec] [common.specs/form-field_required/form-field_required.html]

02:11:52.278 - [spec] [common.specs/form-field_message_text/form-field_message_text.html]

02:11:52.280 - [spec] [common.specs/form-field_message_popup/form-field_message_popup.html]

02:11:52.282 - [spec] [common.specs/form-field/form-field.html]

02:11:52.286 - [spec] [common.specs/form_message_text/form_message_text.html]

02:11:52.289 - [spec] [common.specs/form_message_popup/form_message_popup.html]

02:11:52.291 - [spec] [common.specs/form/form.html]

02:11:52.299 - [spec] [common.specs/message_type_popup/message_type_popup.html]

02:11:52.302 - [spec] [common.specs/form-field_validate_email/form-field_validate_email.html]

02:11:52.307 - [spec] [common.specs/form-field_validate_card/form-field_validate_card.html]

02:11:52.309 - [spec] [common.specs/form-field_type_textarea/form-field_type_textarea.html]

02:11:52.311 - [spec] [common.specs/form-field_type_select/form-field_type_select.html]

02:11:52.312 - [spec] [common.specs/form-field_type_radio/form-field_type_radio.html]

02:11:52.314 - [spec] [common.specs/form-field_type_radio-group/form-field_type_radio-group.html]

02:11:52.316 - [spec] [common.specs/form-field_type_input/form-field_type_input.html]

02:11:52.316 - [spec] [common.specs/form-field_type_hidden/form-field_type_hidden.html]

02:11:52.319 - [spec] [common.specs/message_type_text/message_type_text.html]

02:11:52.320 - [spec] [common.specs/validation_pattern/validation_pattern.html]

02:11:52.320 - [spec] [common.specs/validation_numbers/validation_numbers.html]

02:11:52.320 - [spec] [common.specs/validation_money/validation_money.html]

02:11:52.320 - [spec] [common.specs/validation_length/validation_length.html]

02:11:52.320 - [spec] [common.specs/validation_email/validation_email.html]

02:11:52.320 - [spec] [common.specs/validation_card/validation_card.html]

02:11:52.320 - [spec] [common.specs/validation/validation.html]

02:11:52.321 - [spec] [common.specs/validation_required/validation_required.html]

02:11:52.321 - build failed
Error: specs: 28 failing
    at /Users/jilizart/bem-forms/node_modules/enb-bem-specs/lib/runner.js:168:31
    at Array.<anonymous> (/Users/jilizart/Sites/Github/bem-forms/node_modules/enb-bem-specs/node_modules/vow/lib/vow.js:711:56)
    at Immediate.callFns (/Users/jilizart/Sites/Github/bem-forms/node_modules/enb-bem-specs/node_modules/vow/lib/vow.js:23:35)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by awinogradov** [comment]
`specs: 28 failing` не наводят на мысли?)

**Comment by JiLiZART** [comment]
Ну это стандартный git clone репозитория, никаких изменений я не вносил

**Comment by awinogradov** [comment]
28 тестов падает же. Криво как-то выводится, но падают тесты, не сборка.

**Comment by JiLiZART** [comment]
Т.е тесты всетаки не работают?

**Comment by awinogradov** [comment]
Ну всымсле? Работают, не проходят просто.

**Comment by JiLiZART** [comment]
Тесты Шрёдингера в общем.
